// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Design", "CA1063:Implement IDisposable Correctly", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Packaging.FuncTest.AllowListVerificationProviderTests.Dispose")]
[assembly: SuppressMessage("Usage", "CA1816:Dispose methods should call SuppressFinalize", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Packaging.FuncTest.AllowListVerificationProviderTests.Dispose")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Packaging.FuncTest.AllowListVerificationProviderTests.GetTrustResultAsync_AuthorSignedPackage_RequirementsAsync(NuGet.Packaging.Signing.SignedPackageVerifierSettings,System.Collections.Generic.IReadOnlyCollection{NuGet.Packaging.Signing.VerificationAllowListEntry},System.Boolean,System.Boolean,System.Int32,System.Int32,System.Object[][])~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Packaging.FuncTest.ClientPolicyTests.CreateSignedPackageAsync(NuGet.Test.Utility.TestDirectory,NuGet.Packaging.FuncTest.ClientPolicyTests.SigningTestType,System.Security.Cryptography.X509Certificates.X509Certificate2,System.Security.Cryptography.X509Certificates.X509Certificate2)~System.Threading.Tasks.Task{System.String}")]
[assembly: SuppressMessage("Usage", "CA1816:Dispose methods should call SuppressFinalize", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Packaging.FuncTest.ClientPolicyTests.Dispose")]
[assembly: SuppressMessage("Design", "CA1063:Implement IDisposable Correctly", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Packaging.FuncTest.ClientPolicyTests.Dispose")]
[assembly: SuppressMessage("Globalization", "CA1307:Specify StringComparison for clarity", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Packaging.FuncTest.PrimarySignatureTests.Load_WithPrimarySignatureWithNoCertificates_ThrowsAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Packaging.FuncTest.RepositoryCountersignatureTests.Test.CreateAsync(System.Security.Cryptography.X509Certificates.X509Certificate2,System.Uri,System.Collections.Generic.IReadOnlyList{System.String})~System.Threading.Tasks.Task{NuGet.Packaging.FuncTest.RepositoryCountersignatureTests.Test}")]
[assembly: SuppressMessage("Globalization", "CA1307:Specify StringComparison for clarity", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Packaging.FuncTest.SignatureTrustAndValidityVerificationProviderTests.GetTrustResultAsync_WithInvalidSignature_ThrowsAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Packaging.FuncTest.SignatureTrustAndValidityVerificationProviderTests.TrustRootCertificate(NuGet.Packaging.Signing.IX509CertificateChain)~System.IDisposable")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Packaging.FuncTest.SigningTestFixture.CreateDefaultTrustedCertificateAuthorityAsync~System.Threading.Tasks.Task{Test.Utility.Signing.CertificateAuthority}")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Packaging.FuncTest.SigningTestFixture.CreateTrustedTestCertificateThatWillExpireSoon~Test.Utility.Signing.TrustedTestCert{Test.Utility.Signing.TestCertificate}")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Packaging.FuncTest.SigningTestFixture.CreateUntrustedTestCertificateThatWillExpireSoon~Test.Utility.Signing.TestCertificate")]
[assembly: SuppressMessage("Design", "CA1063:Implement IDisposable Correctly", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Packaging.FuncTest.SigningTestFixture.Dispose")]
[assembly: SuppressMessage("Usage", "CA1816:Dispose methods should call SuppressFinalize", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Packaging.FuncTest.SigningTestFixture.Dispose")]
[assembly: SuppressMessage("Globalization", "CA1307:Specify StringComparison for clarity", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Packaging.FuncTest.SigningUtilityTests.SignAsync_WhenRepositoryCountersigningRepositoryCountersignedPackage_ThrowsAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Globalization", "CA1307:Specify StringComparison for clarity", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Packaging.FuncTest.SigningUtilityTests.SignAsync_WhenRepositoryCountersigningRepositorySignedPackage_ThrowsAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Globalization", "CA1307:Specify StringComparison for clarity", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Packaging.FuncTest.SigningUtilityTests.SignAsync_WithExpiredCertificate_ThrowsAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Globalization", "CA1307:Specify StringComparison for clarity", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Packaging.FuncTest.SigningUtilityTests.SignAsync_WithNotYetValidCertificate_ThrowsAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Globalization", "CA1307:Specify StringComparison for clarity", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Packaging.FuncTest.TimestampProviderTests.GetTimestampAsync_TimestampGeneralizedTimeOutsideCertificateValidityPeriod_FailAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Globalization", "CA1307:Specify StringComparison for clarity", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Packaging.FuncTest.TimestampProviderTests.GetTimestampAsync_WhenLoggerNull_ThrowsAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Globalization", "CA1307:Specify StringComparison for clarity", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Packaging.FuncTest.TimestampProviderTests.GetTimestampAsync_WhenRequestNull_ThrowsAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Globalization", "CA1307:Specify StringComparison for clarity", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Packaging.FuncTest.TimestampProviderTests.GetTimestampAsync_WhenSigningCertificateNotReturned_ThrowsAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Globalization", "CA1307:Specify StringComparison for clarity", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Packaging.FuncTest.TimestampProviderTests.GetTimestampAsync_WithFailureReponse_ThrowsAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Packaging.FuncTest.TimestampTests.Timestamp_Verify_WithOfflineRevocation_ReturnsCorrectFlagsAndLogsAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Design", "CA1063:Implement IDisposable Correctly", Justification = "<Pending>", Scope = "type", Target = "~T:NuGet.Packaging.FuncTest.AllowListVerificationProviderTests")]
[assembly: SuppressMessage("Design", "CA1063:Implement IDisposable Correctly", Justification = "<Pending>", Scope = "type", Target = "~T:NuGet.Packaging.FuncTest.ClientPolicyTests")]
[assembly: SuppressMessage("Design", "CA1063:Implement IDisposable Correctly", Justification = "<Pending>", Scope = "type", Target = "~T:NuGet.Packaging.FuncTest.SigningTestFixture")]
