// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Performance", "CA1802:Use literals where appropriate", Justification = "<Pending>", Scope = "member", Target = "~F:NuGet.Build.Tasks.Test.GetRestoreSettingsTaskTests.DisableSourceConfig")]
[assembly: SuppressMessage("Performance", "CA1802:Use literals where appropriate", Justification = "<Pending>", Scope = "member", Target = "~F:NuGet.Build.Tasks.Test.GetRestoreSettingsTaskTests.InnerConfig")]
[assembly: SuppressMessage("Performance", "CA1802:Use literals where appropriate", Justification = "<Pending>", Scope = "member", Target = "~F:NuGet.Build.Tasks.Test.GetRestoreSettingsTaskTests.MachineWideSettingsConfig")]
[assembly: SuppressMessage("Performance", "CA1802:Use literals where appropriate", Justification = "<Pending>", Scope = "member", Target = "~F:NuGet.Build.Tasks.Test.GetRestoreSettingsTaskTests.OuterConfig")]
[assembly: SuppressMessage("Performance", "CA1802:Use literals where appropriate", Justification = "<Pending>", Scope = "member", Target = "~F:NuGet.Build.Tasks.Test.GetRestoreSettingsTaskTests.ProjectLevelConfig")]
[assembly: SuppressMessage("Performance", "CA1802:Use literals where appropriate", Justification = "<Pending>", Scope = "member", Target = "~F:NuGet.Build.Tasks.Test.GetRestoreSettingsTaskTests.RootConfig")]
[assembly: SuppressMessage("Design", "CA1051:Do not declare visible instance fields", Justification = "<Pending>", Scope = "member", Target = "~F:NuGet.Build.Tasks.Test.TestBuildEngine.TestLogger")]
[assembly: SuppressMessage("Globalization", "CA1307:Specify StringComparison for clarity", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Build.Tasks.Test.GetCentralPackageVersionsTaskTests.Execute_CheckMetadata")]
[assembly: SuppressMessage("Performance", "CA1825:Avoid zero-length array allocations", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Build.Tasks.Test.GetReferenceNearestTargetFrameworkTaskTest.GetReferenceNearestTargetFrameworkTask_WithInvalidParameters_Errors(System.String,System.String,System.String,System.String,System.String)")]
[assembly: SuppressMessage("Performance", "CA1825:Avoid zero-length array allocations", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Build.Tasks.Test.GetReferenceNearestTargetFrameworkTaskTest.GetReferenceNearestTargetFrameworkTask_WithTargetFrameworkInformation_ReturnsCompatibleAlias(System.String,System.String,System.String,System.String,System.String,System.String)")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Build.Tasks.Test.GetReferenceNearestTargetFrameworkTaskTest.GetReferenceNearestTargetFrameworkTask_WithTargetFrameworkInformation_WhenATFMatches_Warns(System.String,System.String,System.String,System.String,System.String,System.String,System.String)")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Build.Tasks.Test.GetReferenceNearestTargetFrameworkTaskTest.GetReferenceNearestTargetFrameworkTask_WithTargetFrameworkInformation_WithAssetTargetFallback_NoMatch(System.String,System.String,System.String,System.String,System.String,System.String)")]
[assembly: SuppressMessage("Performance", "CA1825:Avoid zero-length array allocations", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Build.Tasks.Test.GetReferenceNearestTargetFrameworkTaskTest.GetReferenceNearestTargetFrameworkTask_WithTargetFrameworkInformation_WithoutMatchingFrameworks_Errors(System.String,System.String,System.String,System.String,System.String)")]
[assembly: SuppressMessage("Globalization", "CA1304:Specify CultureInfo", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Build.Tasks.Test.GetRestoreProjectStyleTaskTests.Execute_WhenProjectStyleSupplied_ReturnsSuppliedProjectStyle(System.Boolean)")]
[assembly: SuppressMessage("Performance", "CA1825:Avoid zero-length array allocations", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Build.Tasks.Test.GetRestoreSettingsTaskTests.GetRestoreSettingsTask_VerifyDisabledSourcesAreExcluded")]
[assembly: SuppressMessage("Performance", "CA1825:Avoid zero-length array allocations", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Build.Tasks.Test.GetRestoreSettingsTaskTests.GetRestoreSettingsTask_VerifyEmptyPerFrameworkSettings")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Build.Tasks.Test.TestBuildEngine.LogErrorEvent(Microsoft.Build.Framework.BuildErrorEventArgs)")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Build.Tasks.Test.TestBuildEngine.LogMessageEvent(Microsoft.Build.Framework.BuildMessageEventArgs)")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Build.Tasks.Test.TestBuildEngine.LogWarningEvent(Microsoft.Build.Framework.BuildWarningEventArgs)")]
[assembly: SuppressMessage("Performance", "CA1825:Avoid zero-length array allocations", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Build.Tasks.Test.WarnForInvalidProjectsTaskTests.WarnForInvalidProjectsTask_NoItemsVerifyNoErrors")]
[assembly: SuppressMessage("Globalization", "CA1307:Specify StringComparison for clarity", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Build.Tasks.Test.WarnForInvalidProjectsTaskTests.WarnForInvalidProjectsTask_SingleInvalidItemsVerifySingleWarning")]
