// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.VisualStudio.Implementation.Test.CachingIServiceBrokerProviderTests.#ctor(Microsoft.VisualStudio.Sdk.TestFramework.GlobalServiceProvider)")]
[assembly: SuppressMessage("Performance", "CA1825:Avoid zero-length array allocations", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.VisualStudio.Implementation.Test.Extensibility.VsFrameworkCompatibilityTests.IVsFrameworkCompatibilityTests.VsFrameworkCompatibility_GetNearestWithWithEmptyFallbackList")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.VisualStudio.Implementation.Test.Extensibility.VsPackageRestorerTests.CreateTarget(NuGet.Configuration.ISettings,NuGet.PackageManagement.ISolutionManager,NuGet.PackageManagement.IPackageRestoreManager,NuGet.PackageManagement.VisualStudio.IVsProjectThreadingService,NuGet.VisualStudio.Telemetry.INuGetTelemetryProvider)~NuGet.VisualStudio.VsPackageRestorer")]
[assembly: SuppressMessage("Globalization", "CA1307:Specify StringComparison for clarity", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.VisualStudio.Implementation.Test.Extensibility.VsPathContextProviderTests.CreatePathContextAsync_WithUnrestoredPackageReference_Throws~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Globalization", "CA1307:Specify StringComparison for clarity", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.VisualStudio.Implementation.Test.Extensibility.VsPathContextProviderTests.CreatePathContextAsync_WithUnrestoredPackagesConfig_Throws~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Globalization", "CA1307:Specify StringComparison for clarity", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.VisualStudio.Implementation.Test.Extensibility.VsSemanticVersionTests.SemanticVersion_ParseVersion_ThrowsIfInvalid(System.String)")]
[assembly: SuppressMessage("Globalization", "CA1307:Specify StringComparison for clarity", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.VisualStudio.Implementation.Test.Extensibility.VsSemanticVersionTests.SemanticVersion_ParseVersion_ThrowsIfNullOrEmpty(System.String)")]
[assembly: SuppressMessage("Maintainability", "CA1507:Use nameof to express symbol names", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.VisualStudio.Implementation.Test.Extensibility.VsSemanticVersionTests.SemanticVersion_ParseVersion_ThrowsIfNullOrEmpty(System.String)")]
[assembly: SuppressMessage("Usage", "CA1816:Dispose methods should call SuppressFinalize", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.VisualStudio.Implementation.Test.PreinstalledRepositoryProviderTests.Dispose")]
[assembly: SuppressMessage("Design", "CA1063:Implement IDisposable Correctly", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.VisualStudio.Implementation.Test.PreinstalledRepositoryProviderTests.Dispose")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.VisualStudio.Implementation.Test.PreinstalledRepositoryProviderTests.TestContext.#ctor(System.String,Microsoft.Win32.RegistryHive)")]
[assembly: SuppressMessage("Globalization", "CA1307:Specify StringComparison for clarity", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.VisualStudio.Implementation.Test.SolutionExplorer.Models.AssetsFileDependenciesSnapshotTests.ParseLibraries_LockFileTargetLibrariesWithDifferentCase_Throws")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.VisualStudio.Implementation.Test.VsPackageSourceProviderTests.CreateTarget(NuGet.Protocol.Core.Types.ISourceRepositoryProvider,NuGet.VisualStudio.Telemetry.INuGetTelemetryProvider)~NuGet.VisualStudio.VsPackageSourceProvider")]
[assembly: SuppressMessage("Design", "CA1063:Implement IDisposable Correctly", Justification = "<Pending>", Scope = "type", Target = "~T:NuGet.VisualStudio.Implementation.Test.PreinstalledRepositoryProviderTests")]
[assembly: SuppressMessage("Design", "CA1001:Types that own disposable fields should be disposable", Justification = "<Pending>", Scope = "type", Target = "~T:NuGet.VisualStudio.Implementation.Test.TestUtilities.TestProjectThreadingService")]
