// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.DependencyResolver.Core.Tests.FindPackageTests.FindPackage_VerifyFindLibraryEntryReturnsOriginalCase~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.DependencyResolver.Core.Tests.FindPackageTests.FindPackage_VerifyFloatingPackageIsRequiredOnlyFromASingleSource~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.DependencyResolver.Core.Tests.FindPackageTests.FindPackage_VerifyMissingListedPackageSucceedsOnRetry~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.DependencyResolver.Core.Tests.FindPackageTests.FindPackage_VerifyMissingListedPackageThrowsNotFound~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.DependencyResolver.Core.Tests.FindPackageTests.FindPackage_VerifyMissingVersionPackageReturnsUnresolved~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.DependencyResolver.Core.Tests.FindPackageTests.FindPackage_VerifyPackageSourcesAreFilteredWhenPackageSourceMappingIsEnabled_Success~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.DependencyResolver.Core.Tests.FindPackageTests.FindPackage_WhenNoPackageSourceMappingIsEnabledForAPackage_Fails~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.DependencyResolver.Core.Tests.GraphOperationsTests.GetNode(System.String,System.String,NuGet.LibraryModel.LibraryDependencyTarget,System.String,NuGet.LibraryModel.LibraryType)~NuGet.DependencyResolver.GraphNode{NuGet.DependencyResolver.RemoteResolveResult}")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.DependencyResolver.Core.Tests.GraphOperationsTests.GetNode(System.String,System.String,NuGet.LibraryModel.LibraryDependencyTarget,System.String,NuGet.LibraryModel.LibraryType)~NuGet.DependencyResolver.GraphNode{NuGet.DependencyResolver.RemoteResolveResult}")]
[assembly: SuppressMessage("Globalization", "CA1308:Normalize strings to uppercase", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.DependencyResolver.Core.Tests.GraphOperationsTests.GetNode(System.String,System.String,NuGet.LibraryModel.LibraryDependencyTarget,System.String,NuGet.LibraryModel.LibraryType)~NuGet.DependencyResolver.GraphNode{NuGet.DependencyResolver.RemoteResolveResult}")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.DependencyResolver.Core.Tests.GraphOperationsTests.GetPackageNode(System.String,System.String,System.String)~NuGet.DependencyResolver.GraphNode{NuGet.DependencyResolver.RemoteResolveResult}")]
[assembly: SuppressMessage("Globalization", "CA1308:Normalize strings to uppercase", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.DependencyResolver.Core.Tests.GraphOperationsTests.GetPackageNode(System.String,System.String,System.String)~NuGet.DependencyResolver.GraphNode{NuGet.DependencyResolver.RemoteResolveResult}")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.DependencyResolver.Core.Tests.GraphOperationsTests.GetPackageNode(System.String,System.String,System.String)~NuGet.DependencyResolver.GraphNode{NuGet.DependencyResolver.RemoteResolveResult}")]
[assembly: SuppressMessage("Globalization", "CA1308:Normalize strings to uppercase", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.DependencyResolver.Core.Tests.GraphOperationsTests.GetProjectNode(System.String)~NuGet.DependencyResolver.GraphNode{NuGet.DependencyResolver.RemoteResolveResult}")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.DependencyResolver.Core.Tests.GraphOperationsTests.GetProjectNode(System.String)~NuGet.DependencyResolver.GraphNode{NuGet.DependencyResolver.RemoteResolveResult}")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.DependencyResolver.Core.Tests.GraphOperationsTests.GetProjectNode(System.String)~NuGet.DependencyResolver.GraphNode{NuGet.DependencyResolver.RemoteResolveResult}")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.DependencyResolver.Core.Tests.GraphOperationsTests.GetUnresolvedNode(System.String,System.String,NuGet.LibraryModel.LibraryDependencyTarget)~NuGet.DependencyResolver.GraphNode{NuGet.DependencyResolver.RemoteResolveResult}")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.DependencyResolver.Core.Tests.GraphOperationsTests.GetUnresolvedNode(System.String,System.String,NuGet.LibraryModel.LibraryDependencyTarget)~NuGet.DependencyResolver.GraphNode{NuGet.DependencyResolver.RemoteResolveResult}")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.DependencyResolver.Core.Tests.RemoteWalkContextTests.CreateRemoteDependencyProvider(System.String)~Moq.Mock{NuGet.DependencyResolver.IRemoteDependencyProvider}")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.DependencyResolver.Core.Tests.ResolverFacts.TestProvider.FindLibraryAsync(NuGet.LibraryModel.LibraryRange,NuGet.Frameworks.NuGetFramework,NuGet.Protocol.Core.Types.SourceCacheContext,NuGet.Common.ILogger,System.Threading.CancellationToken)~System.Threading.Tasks.Task{NuGet.LibraryModel.LibraryIdentity}")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.DependencyResolver.Tests.RemoteDependencyWalkerTests.AssertPath``1(NuGet.DependencyResolver.GraphNode{``0},System.String[])")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.DependencyResolver.Tests.RemoteDependencyWalkerTests.DoWalkAsync(NuGet.DependencyResolver.RemoteDependencyWalker,System.String,NuGet.Frameworks.NuGetFramework)~System.Threading.Tasks.Task{NuGet.DependencyResolver.GraphNode{NuGet.DependencyResolver.RemoteResolveResult}}")]
