// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Msbuild.Integration.Test.MsbuildIntegrationTestFixture.DeleteDirectory(System.String)")]
[assembly: SuppressMessage("Design", "CA1063:Implement IDisposable Correctly", Justification = "<Pending>", Scope = "member", Target = "~M:Msbuild.Integration.Test.MsbuildIntegrationTestFixture.Dispose")]
[assembly: SuppressMessage("Usage", "CA1816:Dispose methods should call SuppressFinalize", Justification = "<Pending>", Scope = "member", Target = "~M:Msbuild.Integration.Test.MsbuildIntegrationTestFixture.Dispose")]
[assembly: SuppressMessage("Globalization", "CA1307:Specify StringComparison for clarity", Justification = "<Pending>", Scope = "member", Target = "~M:Msbuild.Integration.Test.MsbuildRestoreTaskTests.MsbuildRestore_InsecurePackagesConfigDependencyAsync_Throws~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Globalization", "CA1307:Specify StringComparison for clarity", Justification = "<Pending>", Scope = "member", Target = "~M:Msbuild.Integration.Test.MsbuildRestoreTaskTests.MsbuildRestore_NoPackageSourceMappingsection_NoSourceRelatedLogMessage~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Globalization", "CA1307:Specify StringComparison for clarity", Justification = "<Pending>", Scope = "member", Target = "~M:Msbuild.Integration.Test.MsbuildRestoreTaskTests.MsbuildRestore_PackageReferenceDependencyAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Globalization", "CA1307:Specify StringComparison for clarity", Justification = "<Pending>", Scope = "member", Target = "~M:Msbuild.Integration.Test.MsbuildRestoreTaskTests.MsbuildRestore_PackageReferenceDependencyCsProjAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Globalization", "CA1307:Specify StringComparison for clarity", Justification = "<Pending>", Scope = "member", Target = "~M:Msbuild.Integration.Test.MsbuildRestoreTaskTests.MsbuildRestore_PackagesConfigDependencyAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Globalization", "CA1307:Specify StringComparison for clarity", Justification = "<Pending>", Scope = "member", Target = "~M:Msbuild.Integration.Test.MsbuildRestoreTaskTests.MsbuildRestore_PackagesConfigIsOptInAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Globalization", "CA1307:Specify StringComparison for clarity", Justification = "<Pending>", Scope = "member", Target = "~M:Msbuild.Integration.Test.MsbuildRestoreTaskTests.MsbuildRestore_PackageSourceMappingLongerMatches_NoNamespaceMatchesLog~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Globalization", "CA1307:Specify StringComparison for clarity", Justification = "<Pending>", Scope = "member", Target = "~M:Msbuild.Integration.Test.MsbuildRestoreTaskTests.MsbuildRestore_PackageSourceMappingLongerMatches_Succeed~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Globalization", "CA1307:Specify StringComparison for clarity", Justification = "<Pending>", Scope = "member", Target = "~M:Msbuild.Integration.Test.MsbuildRestoreTaskTests.MsbuildRestore_PR_PackageSourceMapping_WithAllRestoreSourceProperies_Succeed~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Globalization", "CA1307:Specify StringComparison for clarity", Justification = "<Pending>", Scope = "member", Target = "~M:Msbuild.Integration.Test.MsbuildRestoreTaskTests.MsbuildRestore_PR_PackageSourceMapping_WithNotEnoughRestoreSourceProperty_Fails~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Globalization", "CA1307:Specify StringComparison for clarity", Justification = "<Pending>", Scope = "member", Target = "~M:Msbuild.Integration.Test.MsbuildRestoreTaskTests.MsbuildRestore_RequiresSolutionDirAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Globalization", "CA1307:Specify StringComparison for clarity", Justification = "<Pending>", Scope = "member", Target = "~M:Msbuild.Integration.Test.MsbuildRestoreTaskTests.MsbuildRestore_WithCPPCliVcxproj_RestoresSuccessfullyWithPackageReference(System.Boolean)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Globalization", "CA1307:Specify StringComparison for clarity", Justification = "<Pending>", Scope = "member", Target = "~M:Msbuild.Integration.Test.MsbuildRestoreTaskTests.MsbuildRestore_WithCPPCliVcxproj_WithAssetTargetFallback_Succeeds~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Globalization", "CA1307:Specify StringComparison for clarity", Justification = "<Pending>", Scope = "member", Target = "~M:Msbuild.Integration.Test.MsbuildRestoreTaskTests.MsbuildRestore_WithCPPCliVcxproj_WithNativeAndManagedTransitiveDependency_Succeeds~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Globalization", "CA1307:Specify StringComparison for clarity", Justification = "<Pending>", Scope = "member", Target = "~M:Msbuild.Integration.Test.MsbuildRestoreTaskTests.MsbuildRestore_WithCPPCliVcxproj_WithNativeDependency_Succeeds~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Design", "CA1063:Implement IDisposable Correctly", Justification = "<Pending>", Scope = "type", Target = "~T:Msbuild.Integration.Test.MsbuildIntegrationTestFixture")]
