// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Performance", "CA1825:Avoid zero-length array allocations", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Commands.FuncTest.RestoreCommand_PackagesLockFileTests.RestoreCommand_PackagesLockFile_InLockedMode_WhenARuntimeIdentifierIsAdded_FailsWithNU1004~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Globalization", "CA1307:Specify StringComparison for clarity", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Commands.FuncTest.RestoreCommandTests.RestoreCommand_FrameworkImport_WarnOnAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Globalization", "CA1307:Specify StringComparison for clarity", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Commands.FuncTest.RestoreCommandTests.RestoreCommand_NoCompatibleRuntimeAssembliesForProjectAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Globalization", "CA1307:Specify StringComparison for clarity", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Commands.FuncTest.RestoreCommandTests.RestoreCommand_RuntimeIdentifierGraph_SelectsCorrectRuntimeAssemblies~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Globalization", "CA1307:Specify StringComparison for clarity", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Commands.FuncTest.RestoreCommandTests.RestoreCommand_UnmatchedRefAndLibAssembliesAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Commands.FuncTest.RestoreCommandTests.RestoreCommand_VerifyMinClientVersionAlreadyInstalledAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Globalization", "CA1307:Specify StringComparison for clarity", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Commands.FuncTest.RestoreCommandTests.RestoreCommand_VerifyMinClientVersionAlreadyInstalledAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Commands.FuncTest.RestoreCommandTests.RestoreCommand_VerifyMinClientVersionLocalFolderAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Globalization", "CA1307:Specify StringComparison for clarity", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Commands.FuncTest.RestoreCommandTests.RestoreCommand_VerifyMinClientVersionLocalFolderAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Commands.FuncTest.RestoreCommandTests.RestoreCommand_VerifyMinClientVersionV2SourceAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Globalization", "CA1307:Specify StringComparison for clarity", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Commands.FuncTest.RestoreCommandTests.RestoreCommand_VerifyMinClientVersionV2SourceAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Globalization", "CA1307:Specify StringComparison for clarity", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Commands.FuncTest.RestoreCommandTests.RestoreCommand_VerifyMinClientVersionV3SourceAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Commands.FuncTest.RestoreCommandTests.RestoreCommand_VerifyMinClientVersionV3SourceAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Globalization", "CA1307:Specify StringComparison for clarity", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Commands.FuncTest.RestoreCommandTests.RestoreCommand_WhenPlatformVersionIsEmpty_ThrowsError~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Globalization", "CA1307:Specify StringComparison for clarity", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Commands.FuncTest.RestoreCommandTests.RestoreCommand_WithFrameworkSpecificRuntimeIdentifierGraph_SelectsCorrectRuntimeAssemblies~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Commands.FuncTest.RestoreCommandTests.RestoreCommand_WithPackageNamesacesConfiguredAndNoMatchingSourceForAPackage_Fails~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Commands.FuncTest.RestoreCommandTests.RestoreCommand_WithPackageNamesacesConfiguredDownloadsPackageFromExpectedSource_Succeeds~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Commands.FuncTest.UWPRestoreTests.RemovePackageFolders(Newtonsoft.Json.Linq.JObject)")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Commands.FuncTest.UWPRestoreTests.RemoveRestoreSection(Newtonsoft.Json.Linq.JObject)")]
